---
verifyConditions:
  - "@semantic-release/git"
  - "@semantic-release/changelog"
prepare:
  - "@semantic-release/changelog"
  - { path: "@semantic-release/exec", cmd: "lein change version set '\"${nextRelease.version}\"'" } 
  - { path: "@semantic-release/git",  assets: ["CHANGELOG.md", "project.clj"] }
publish:
  - { path: "@semantic-release/exec", cmd: "lein deploy clojars" }
success: []
fail: []
