---
verifyConditions:
  - "@semantic-release/git"
  - "@semantic-release/changelog"
prepare:
  - "@semantic-release/changelog"
  - { path: "@semantic-release/exec", cmd: "lein set-version ${nextRelease.version}" } 
  - "@semantic-release/git"
publish:
  - { path: "@semantic-release/exec", cmd: "lein deploy clojars" }
success: []
fail: []
