version: 2
jobs:
  test:
    docker:
      - image: circleci/clojure:lein-2.9.3
    steps:
      - checkout
      - restore_cache:
          key: v1-{{checksum "project.clj"}}
      - run: lein test
      - save_cache:
          key: v1-{{checksum "project.clj"}}
          paths:
            - ~/.m2

  release:
    docker:
      - image: circleci/clojure:lein-2.9.3-node
    steps:
      - checkout
      - restore_cache:
          key: v1-{{checksum "project.clj"}}
      - run: |
          git config user.email "miikka.koskinen+ci@iki.fi"
          git config user.name  "Build automation"
      - run: |
          ./scripts/decrypt-secrets.sh "$SECRETS_PASSPHRASE"
          gpg --import secrets/signing-key.asc
          mkdir -p ~/.lein && cp secrets/profiles.clj ~/.lein/
      - add_ssh_keys:
          fingerprints:
            - "4c:ad:91:8f:3d:1f:27:44:73:1a:ce:ad:18:d2:5e:46"
      - run: npm install
      - run: ./node_modules/.bin/semantic-release

workflows:
  version: 2
  test_and_release:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only:
                - master
