version: 2
jobs:
  test:
    docker:
      - image: circleci/clojure:lein-2.8.1
    steps:
      - checkout
      - restore_cache:
          key: v1-{{checksum "project.clj"}}
      - run: lein test
      - save_cache:
          key: v1-{{checksum "project.clj"}}
          paths:
            - ~/.m2

  release:
    docker:
      - image: circleci/clojure:lein-2.8.1-node
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "37:eb:61:ba:1c:54:99:96:a3:c0:c2:3f:a4:cb:49:f8"
      - run: npx semantic-release@15

workflows:
  version: 2
  test_and_release:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only:
                - master
